CREATE TABLE OPERADORAS_ATIVAS (
    ID SERIAL PRIMARY KEY,
    REGISTRO_ANS VARCHAR(20) UNIQUE,
    CNPJ VARCHAR(18),
    RAZAO_SOCIAL VARCHAR(255),
    NOME_FANTASIA VARCHAR(255),
    MODALIDADE VARCHAR(100),
    LOGADOURO VARCHAR(255),
    NUMERO VARCHAR(255),
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(255),
    CIDADE VARCHAR(255),
    UF VARCHAR(2),
    CEP VARCHAR(50)
    DDD VARCHAR(2),
    TELEFONE VARCHAR(50),
    FAX VARCHAR(50),
    ENDERECO_ELETRONICO VARCHAR(255),
    REPRESENTANTE VARCHAR(255),
    CARGO_REPRESENTANTE VARCHAR(255),
    REGIAO_DE_COMERCIO VARCHAR(255),
    DATA_REGISTRO_ANS VARCHAR(255),
    MUNICIPIO VARCHAR(100)
);

CREATE TABLE demonstracoes_contabeis (
    ID SERIAL PRIMARY KEY,
    ANO DATA,
    REG_ANS VARCHAR(20),
    CD_CONTA_CONTABIL VARCHAR(255),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL NUMERIC,
    VL_SALDO_FINAL NUMERIC
);
